//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 12:23:32 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ecb.int/vocabulary/2002-08-01/eurofxref", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.alextrandafir.fx.ws;
